CC=gcc

all: Assignment1 Assignment2 Assignment3 Assignment4

Assignment1: Assignment1.c
	$(CC) -o Assignment1 Assignment1.c

Assignment2: Assignment2.c
	$(CC) -o Assignment2 Assignment2.c

Assignment3: Assignment3.c
	$(CC) -o Assignment3 Assignment3.c

Assignment4: Assignment4.c
	$(CC) -o Assignment4 Assignment4.c
